name: terraform
on:
  # Triggers the workflow on push or pull request events but only for the "terraform" branch
  push:
    branches: [ "terraform" ]
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.REGION}}

      - name: Create s3 bucket
        run: aws s3 mb s3://izikcapstoneproject24

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Install helm
        uses: azure/setup-helm@v4.2.0

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
# create cluster   
      - name: Create EKS cluster
        run: |
          terraform -chdir=terraform/ init
          terraform -chdir=terraform apply --auto-approve
# update kubeconfig file to match eks cluster created
      - name: Update kubeconfig 
        run: |
          aws eks update-kubeconfig -name=socks-shop-cluster --region=us-east-1
          kubectl create namespace sock-shop
          